from .text_strings_util import make_string_for_output, deleting_photo_from_list, make_promo_string
from .message_utils import make_output_album
from .admin_change_callback import StorageForChangePlaceData
from .admin_change_callback import StorageForChangeImageData

from .admin_change_callback import StorageForDeletingCategory, StorageForChangingContacts
